### ISSUE TITLE
incoming message 2 widget count sum

### ISSUE THREAD

**Issue by raydelgg** [felixb/callmeter#88] opened 2015-09-30 13:13 UTC
first of all sorry for my English
i'm ussing a sony xperiaz c6603 (android 5.1.1)
the incomming message counter 2 show inside de app the shows the right number, but in the widget 
it shows a summation of all messages no matter month.
it seems that only about this item

![screenshot_2015-09-30-09-04-25](https://cloud.githubusercontent.com/assets/14906926/10193848/124ac850-674b-11e5-982c-d276d9ad6b45.png)
![screenshot_2015-09-30-09-04-39](https://cloud.githubusercontent.com/assets/14906926/10193849/12be19b8-674b-11e5-9e92-dff8167191bb.png)
regards Raydel

**Comment by felixb** [comment] 2015-10-08 16:47
the widgets are a bit lazy with updates. is this problem persistent?

**Comment by raydelgg** [comment] 2015-10-08 17:01
yes it is, that widget show a sum of all incoming message, no matter the period or month

**Comment by felixb** [comment] 2017-12-16 19:32
I can't reproduce the issue. I'll close it for now. Mainly because of the age of it.

**Closed by felixb** 2017-12-16 19:32 UTC
Labels: waiting-for-info
