### ISSUE TITLE
Feature request: include from calls "not solved"

### ISSUE THREAD

**Issue by NEERAJ-YADAV** [felixb/callmeter#108] opened 2016-04-16 07:45 UTC
There is no "include number" setting above exclude number.
I am posting the screenshot. I am talking about preference then advance preferences then number groups.
Please read my previously closed post to catch the exact issue.
![screenshot_2016-04-16-12-59-46](https://cloud.githubusercontent.com/assets/18465448/14579766/06d33d74-03d4-11e6-890e-f384fec62132.png)
![screenshot_2016-04-16-12-59-29](https://cloud.githubusercontent.com/assets/18465448/14579767/06d5db1a-03d4-11e6-9db8-ea2c15d1a191.png)

**Comment by felixb** [comment] 2016-04-16 16:21
Duplicate of #107

**Closed by felixb** 2016-04-16 16:21 UTC
