### ISSUE TITLE
4×1 widget (feature addition)

### ISSUE THREAD

**Issue by MrGreenDXB** [felixb/callmeter#58] opened 2015-02-16 20:59 UTC
It would be good to have a widget of size 4 x 1, rather than current 1 × 1. 
This would help to see the same data we see on opening the app, on the home screen. The displayable fields should be configurable.

**Comment by felixb** [comment] 2015-02-17 05:39
duplicate of #5

**Closed by felixb** 2015-02-17 05:39 UTC
Labels: duplicate
